### ISSUE TITLE
Typo in 4.1

### ISSUE THREAD

**Issue by PetrPalisek** [Lakens/statistical_inferences#102]
Hi,
I think there is a typo in chapter 4.1.

Original: Bayesian statistics the probability of data under a specified model (P|D() is a number that expressed what is sometimes referred to as the absolute evidence

Correct: Bayesian statistics the probability of data under a specified model P(D|H) is a number that expressed what is sometimes referred to as the absolute evidence

**Comment by Lakens** [comment]
Hi, I only see it misses a closing parenthesis in the online version. Are you using a pdf? I do not k ow why the math does not render for you.

________________________________
From: PetrPalisek ***@***.***>
Sent: Sunday, October 22, 2023 11:40:54 PM
To: Lakens/statistical_inferences ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Lakens/statistical_inferences] Typo in 4.1 (Issue #102)


Hi,
I think there is a typo in chapter 4.1.

Original: Bayesian statistics the probability of data under a specified model (P|D() is a number that expressed what is sometimes referred to as the absolute evidence

Correct: Bayesian statistics the probability of data under a specified model P(D|H) is a number that expressed what is sometimes referred to as the absolute evidence

**Comment by PetrPalisek** [comment]
Hi, 
here's a screenshot.

￼

It's the web version: https://lakens.github.io/statistical_inferences/04-bayes.html

And I am using Safari.

P.

**Comment by Lakens** [comment]
Thanks! Then I guess it does not work on your safari setup. It shows up fine on my phone and desktop.  I have never heard this before so it might be some specific settings on your end, as Safari is used more widely, and a lot of students have used this book. There is nothing I can do about it, I fear.

________________________________

**Comment by Lakens** [comment]
Ps your screenshot is also not visible to me.

**Comment by PetrPalisek** [comment]
Yeah, might be! Good thing the rest of the book works.

Here is the screenshot: https://ibb.co/2NT1qmY

**Comment by Lakens** [comment]
We have misunderstood each other. In your copy pasted issue the H0 was missing from the formula! Now I see that is not at all what you meant!

________________________________

**Comment by Lakens** [comment]
So, I think I do not understand what your issue is. Can you explain? The screenshot has H0 in there. And yet, that is the change you made in your issue. I am confused what your problem is. Can you explain it like I am 4?

________________________________

**Comment by Lakens** [comment]
Ah! Yes I get it now. Will fix it. Was on my phone traveling to Germany, so difficult to get it.

________________________________

**Comment by PetrPalisek** [comment]
Great! :)

Thanks.
