### ISSUE TITLE
repeating words

### ISSUE THREAD

**Issue by SocQuant** [Lakens/statistical_inferences#22]
Dear Daniel,

thank you very much for sharing your great work with us.

here is a repeating of words in this sentence:

"However, in any sample drawn draw from the population, random variation is very likely to lead to a difference somewhat larger or smaller than 0. "

if I see more I am going to share it with you

Best regards
Hilal

**Comment by Lakens** [comment]
Thanks! If you could add the chapter where the error is in, that makes it easier to find. Fixed!
