### ISSUE TITLE
False p-value in 9.1 Equivalence Tests

### ISSUE THREAD

**Issue by Julsten** [Lakens/statistical_inferences#24]
Hey Daniël,
great book, thank you for putting in so much effort!

I found a minor mistake regarding the p-value in line 156 (p = 0.326) coming from `r round(res$TOST$p[2],3)` . I believe, this is the p-value from the TOSTER-Results before. I think putting the analysis from lines 158 to 165 before the text in line 156 should do the trick :)

Cheers!
Julian

**Comment by Lakens** [comment]
Thanks, fixed now.
