### ISSUE TITLE
Answers to questions

### ISSUE THREAD

**Issue by thewchan** [Lakens/statistical_inferences#28]
Would it be possible to provide the answers to the end-of-chapter questions? This will really help me when studying as I can attempt the questions first and verify I understood the concepts. (Apologies if the answers were included and I missed them.) Thanks!

**Comment by Lakens** [comment]
Hi, the answers are not provided. These questions are used for summative tests for the students I teach. As with most textbooks, I would prefer it as author when students can't find the answers online :) Maybe that is naive, but that's how it is for now.

**Comment by thewchan** [comment]
Got it, that makes total sense. Appreciate it regardless!
