### ISSUE TITLE
Question: pdf version?

### ISSUE THREAD

**Issue by mario-bermonti** [Lakens/statistical_inferences#32]
Thanks for this awesome resource. I am considering including the book in my courses. I know students could read it online, but is  it possible you could share a “compiled” pdf version of the book?

I think it would help students highlight content and take notes directly in the book source.

**Comment by Lakens** [comment]
See #23 https://github.com/Lakens/statistical_inferences/issues/23

**Comment by Lakens** [comment]
See the docs folder.

**Comment by mario-bermonti** [comment]
You are right. I had checked the repo’s folders and did not see it and I did not review the issues that have already been closed. Sorry, my bad 😅
