### ISSUE TITLE
Minor typo on Line 75

### ISSUE THREAD

**Issue by cirxi** [Lakens/statistical_inferences#34]
Hi Dr Lakens,

Enjoying the book so far, just wanted to point out a minor typo on Line 75, specifically: 

> At the same time, the alpha of 5% guarantees that (in the long run) 5% of the 100 studies where the null hypothesis is true are Type 1 errors: **5%\*100 = 0.05**.

I believe this should be `5%\*100 = 5` (or `0.05\*100 = 5` to be congruent with the 200 study example).

**Comment by Lakens** [comment]
Thanks, you are right - I have fixed it (it might take some days to appear, I push new updates when there are a bunch of changes). Keep m coming!
