### ISSUE TITLE
Minor typo on Line 426 of 02-errorcontrol.Rmd

### ISSUE THREAD

**Issue by cirxi** [Lakens/statistical_inferences#35]
Hi Dr Lakens,

Found another minor typo in Chapter 2.
https://github.com/Lakens/statistical_inferences/blob/cad0a3dac36f1f68b0d2e0b540fc4343853aed69/02-errorcontrol.Rmd#L426

Second sentence of this line:
> "... Even ~thought~ though the topic of Type 2 error control is only briefly discussed here ..."

**Comment by Lakens** [comment]
thanks! Incorporated
