### ISSUE TITLE
Dead link to 'online bayes factor calculator'

### ISSUE THREAD

**Issue by daaronr** [Lakens/statistical_inferences#37]
> You can check this in an [online Bayes Factor calculator](http://pcl.missouri.edu/bf-binomial) ([Rouder et al., 2009](https://lakens.github.io/statistical_inferences/references.html#ref-rouder_bayesian_2009)). At successes, fill

The link is dead for me

**Comment by Lakens** [comment]
It is indeed dead, but I doubt it will stay dead - this calculator is widely used and has been there for years. Let's see if they fix it

**Comment by daaronr** [comment]
Thanks. 

I 2)

**Comment by Lakens** [comment]
The calculator is still not fixed. I will just remove this check from the textbook until it is fixed.
