### ISSUE TITLE
minor typo in chapter 1.4?

### ISSUE THREAD

**Issue by PPoggel** [Lakens/statistical_inferences#38]
Hey Dr. Lakens, 

I think there is a minor typo in chapter 1.4 line 146: 

> In the simulation, we generate n = 71 normally distributed IQ scores with a mean of M (106 by default) and a standard deviation of 15. We then perform a one-sample *t*-test and store the *p*-value. 

The code chunk from line 133 to 143: 
<img width="802" alt="grafik" src="https://user-images.githubusercontent.com/105673990/170855636-39b41513-2cd8-4674-b4f3-8836fb0d2e4d.png">

In the simulation, we generate n = 71 normally distributed IQ scores with a mean of M (**_105 by default)_** and a standard deviation of 15. We then perform a one-sample *t*-test and store the *p*-value. 

As I've said before your textbook is awesome (especially as a preparation for my master's degree) :)

**Comment by Lakens** [comment]
Good catch - I changed the example somhere through writing, but forgot to change this value in the text. Will update the book now.
