### ISSUE TITLE
missing word in text

### ISSUE THREAD

**Issue by DocGavin** [Lakens/statistical_inferences#53]
at start of ch 3 this sentence has a missing word 
i've inserted it in bold, square brackets where it belongs.
cheers

Like [Bayesian approaches](https://lakens.github.io/statistical_inferences/bayes), which will be discussed in the next chapter, likelihoodists are interested **[in]** quantifying a measure of relative evidence when comparing two models or hypotheses.

**Comment by Lakens** [comment]
Thanks! Fixed now.
