### ISSUE TITLE
Minor wording error in Section 9.2 Reporting equivalence tests

### ISSUE THREAD

**Issue by drcpennington** [Lakens/statistical_inferences#63]
Hey Daniel, I am reading you chapter on Equivalence Tests in your OA book. It's fantastic! I've spotted a minor error under Section 9.2 Reporting equivalence tests: it reads "If both a null hypothesis test and a significant test are non-significant, the finding is best described as 'inconclusive'". Shouldn't the sentence read "If both a null hypothesis test and an **equivalence** test are non-significant, the finding is best described as 'inconclusive" (rather than a "significant test"). Best wishes, Charlotte

**Comment by Lakens** [comment]
thanks for the feedback!
