### ISSUE TITLE
Mistyping errors on Chapter 2 and 5

### ISSUE THREAD

**Issue by rafavsbastos** [Lakens/statistical_inferences#85]
In Chapter 2 on Error Control, writing about 2.2 Positive predictive value, the fourth line states "They key to understanding this difference is that two different probabilities are calculated.". "They key" maybe should be "The key".

In Chapter 5 on Asking Statistical Questions, writing about 5.2 Prediction, the example "For example, during the COVID-9 pandemic a large number of models (...)". "COVID-9" maybe should be "COVID-19.

**Comment by Lakens** [comment]
thanks, fixed
