### ISSUE TITLE
PDF and epub versions are not available anymore

### ISSUE THREAD

**Issue by yasharz** [Lakens/statistical_inferences#89]
Hi,

Thank you for making your book and lectures publicly available, they are really helpful!
I was trying to get the PDF/epub to read it on my e-reader but the links are broken.

Best,
Yashar

**Comment by Lakens** [comment]
Why do you want a PDF? There is an outdated version here https://github.com/Lakens/statistical_inferences/raw/master/docs/statistical_inferences_book.pdf 
But the PDF is hugely inferior to the HTML. It is just a much worse version with many missing aspect of the book - why would you want it? I do not really want people to read the book in any other way than HTML.

**Comment by yasharz** [comment]
Thanks for your quick response. I want the epub (or PDF) to read it on my Kindle but I understand that the html format which is updated is preferable.

**Comment by Lakens** [comment]
OK - I made a pdf and epud version for you anyway, they are now under the download buttons!
