### ISSUE TITLE
Error(?) in answer to question 9 in 1.8.2

### ISSUE THREAD

**Issue by ajcullum** [Lakens/statistical_inferences#98]
Hi! Enjoying your work, as always.

I believe that question 9 in 1.8.2 (Questions about p-value misconceptions) has an incorrect answer marked as correct:

Q9: Which statement is true?

Marked as correct: 
he probability that a replication study will yield a significant result is 1-p multiplied by the probability that the null hypothesis is true. _Note that the initial "T" is missing in the text, so that typo should be correct as well_

Actual correct answer(?) should be:
The probability that a replication study will yield a significant result is equal to the statistical power of the replication study (if there is a true effect), or the alpha level (if there is no true effect).

Thanks,
Alistair

**Comment by Lakens** [comment]
you are right, thanks for spotting, will fix it in a few minutes
